@url_dev=http://localhost:3000/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: ede28364db509cce622633ef58998cf53c6641b957391f1aeab6da9c28ce2933b229806b9c19b01c093080e7c8ac6bef43fc6f997a83e10c573d60f47b543cc5

{
  "name": "test",
  "email": "test1222222dsad2",
  "password": "test"
}


### signin
POST {{url_dev}}/shop/signin
Content-Type: application/json
x-api-key: ede28364db509cce622633ef58998cf53c6641b957391f1aeab6da9c28ce2933b229806b9c19b01c093080e7c8ac6bef43fc6f997a83e10c573d60f47b543cc5

{
  "email": "test1222222dsad2",
  "password": "test"
}

### logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: ede28364db509cce622633ef58998cf53c6641b957391f1aeab6da9c28ce2933b229806b9c19b01c093080e7c8ac6bef43fc6f997a83e10c573d60f47b543cc5
x-client-id: 676ae0faaa7dce0980af444f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhZTBmYWFhN2RjZTA5ODBhZjQ0NGYiLCJlbWFpbCI6InRlc3QxMjIyMjIyZHNhZDIiLCJpYXQiOjE3MzUyMzA0MDUsImV4cCI6MTczNTQwMzIwNX0.9QIdkhnQoJf7t-jo_16wE2gEt5qKqXhyaPKrePWd85k

### refresh-token
POST {{url_dev}}/shop/refresh-token
Content-Type: application/json
x-api-key: ede28364db509cce622633ef58998cf53c6641b957391f1aeab6da9c28ce2933b229806b9c19b01c093080e7c8ac6bef43fc6f997a83e10c573d60f47b543cc5
x-client-id: 676ae0faaa7dce0980af444f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhZTBmYWFhN2RjZTA5ODBhZjQ0NGYiLCJlbWFpbCI6InRlc3QxMjIyMjIyZHNhZDIiLCJpYXQiOjE3MzU2NjI2MjAsImV4cCI6MTczNTgzNTQyMH0.Y-9zzLw3enWxjlNlFiS4EkWW4yGGjWv68NA194Qd_d4

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhZTBmYWFhN2RjZTA5ODBhZjQ0NGYiLCJlbWFpbCI6InRlc3QxMjIyMjIyZHNhZDIiLCJpYXQiOjE3MzU2NjI2MjAsImV4cCI6MTczNjI2NzQyMH0.ILvON_Fin-eroBN0tZ8YdCOsNYGlD5bh-h4BoMHyZEo"
}