@url_dev=http://localhost:3000/v1/api

### Create Product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: ede28364db509cce622633ef58998cf53c6641b957391f1aeab6da9c28ce2933b229806b9c19b01c093080e7c8ac6bef43fc6f997a83e10c573d60f47b543cc5
x-client-id: 676ae0faaa7dce0980af444f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhZTBmYWFhN2RjZTA5ODBhZjQ0NGYiLCJlbWFpbCI6InRlc3QxMjIyMjIyZHNhZDIiLCJpYXQiOjE3MzY4NzM3ODgsImV4cCI6MTczNzA0NjU4OH0.r_PeR2Bp-7RL8ShRj_h6Ts9tInaOKDKwxRgauck1gas

{
  "product_name": "Test",
  "product_description": "Test",
  "product_price": 100,
  "product_shop": "676ae0faaa7dce0980af444f",
  "product_type": "Clothing",
  "product_thumb": "product_thumb",
  "product_quantity": 10,
  "product_attributes": {
      "brand": "Levis",
      "size": "L",
      "material": "Cotton"
  }
}